package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;

/**
 * Accounts generated by hbm2java
 */
public class Accounts  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String email;
     private String userGroup;
     private String fullName;
     private String address;
     private String dateOfBirth;
     private String phoneNumber;
     private Integer status;
     private Set customerInvoiceses = new HashSet(0);
     private Set supplierses = new HashSet(0);
     private Set catererses = new HashSet(0);

    public Accounts() {
    }

	
    public Accounts(int id) {
        this.id = id;
    }
    public Accounts(int id, String username, String password, String email, String userGroup, String fullName, String address, String dateOfBirth, String phoneNumber, Integer status, Set customerInvoiceses, Set supplierses, Set catererses) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.email = email;
       this.userGroup = userGroup;
       this.fullName = fullName;
       this.address = address;
       this.dateOfBirth = dateOfBirth;
       this.phoneNumber = phoneNumber;
       this.status = status;
       this.customerInvoiceses = customerInvoiceses;
       this.supplierses = supplierses;
       this.catererses = catererses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserGroup() {
        return this.userGroup;
    }
    
    public void setUserGroup(String userGroup) {
        this.userGroup = userGroup;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getCustomerInvoiceses() {
        return this.customerInvoiceses;
    }
    
    public void setCustomerInvoiceses(Set customerInvoiceses) {
        this.customerInvoiceses = customerInvoiceses;
    }
    public Set getSupplierses() {
        return this.supplierses;
    }
    
    public void setSupplierses(Set supplierses) {
        this.supplierses = supplierses;
    }
    public Set getCatererses() {
        return this.catererses;
    }
    
    public void setCatererses(Set catererses) {
        this.catererses = catererses;
    }




}


