package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1



/**
 * CustomerChildInvoices generated by hbm2java
 */
public class CustomerChildInvoices  implements java.io.Serializable {


     private int id;
     private CustomerInvoices customerInvoices;
     private String foodName;

    public CustomerChildInvoices() {
    }

	
    public CustomerChildInvoices(int id) {
        this.id = id;
    }
    public CustomerChildInvoices(int id, CustomerInvoices customerInvoices, String foodName) {
       this.id = id;
       this.customerInvoices = customerInvoices;
       this.foodName = foodName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CustomerInvoices getCustomerInvoices() {
        return this.customerInvoices;
    }
    
    public void setCustomerInvoices(CustomerInvoices customerInvoices) {
        this.customerInvoices = customerInvoices;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }




}


