package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomerInvoices generated by hbm2java
 */
public class CustomerInvoices  implements java.io.Serializable {


     private int id;
     private Accounts accounts;
     private Caterers caterers;
     private Workers workers;
     private String invoiceDate;
     private Double costPerPlate;
     private Integer numberOfPlate;
     private String deliveryDate;
     private String deliveryName;
     private String deliveryEmail;
     private String deliveryPhoneNumber;
     private String deliveryAddress;
     private String status;
     private Set customerChildInvoiceses = new HashSet(0);

    public CustomerInvoices() {
    }

	
    public CustomerInvoices(int id) {
        this.id = id;
    }
    public CustomerInvoices(int id, Accounts accounts, Caterers caterers, Workers workers, String invoiceDate, Double costPerPlate, Integer numberOfPlate, String deliveryDate, String deliveryName, String deliveryEmail, String deliveryPhoneNumber, String deliveryAddress, String status, Set customerChildInvoiceses) {
       this.id = id;
       this.accounts = accounts;
       this.caterers = caterers;
       this.workers = workers;
       this.invoiceDate = invoiceDate;
       this.costPerPlate = costPerPlate;
       this.numberOfPlate = numberOfPlate;
       this.deliveryDate = deliveryDate;
       this.deliveryName = deliveryName;
       this.deliveryEmail = deliveryEmail;
       this.deliveryPhoneNumber = deliveryPhoneNumber;
       this.deliveryAddress = deliveryAddress;
       this.status = status;
       this.customerChildInvoiceses = customerChildInvoiceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Caterers getCaterers() {
        return this.caterers;
    }
    
    public void setCaterers(Caterers caterers) {
        this.caterers = caterers;
    }
    public Workers getWorkers() {
        return this.workers;
    }
    
    public void setWorkers(Workers workers) {
        this.workers = workers;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public Double getCostPerPlate() {
        return this.costPerPlate;
    }
    
    public void setCostPerPlate(Double costPerPlate) {
        this.costPerPlate = costPerPlate;
    }
    public Integer getNumberOfPlate() {
        return this.numberOfPlate;
    }
    
    public void setNumberOfPlate(Integer numberOfPlate) {
        this.numberOfPlate = numberOfPlate;
    }
    public String getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getDeliveryName() {
        return this.deliveryName;
    }
    
    public void setDeliveryName(String deliveryName) {
        this.deliveryName = deliveryName;
    }
    public String getDeliveryEmail() {
        return this.deliveryEmail;
    }
    
    public void setDeliveryEmail(String deliveryEmail) {
        this.deliveryEmail = deliveryEmail;
    }
    public String getDeliveryPhoneNumber() {
        return this.deliveryPhoneNumber;
    }
    
    public void setDeliveryPhoneNumber(String deliveryPhoneNumber) {
        this.deliveryPhoneNumber = deliveryPhoneNumber;
    }
    public String getDeliveryAddress() {
        return this.deliveryAddress;
    }
    
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getCustomerChildInvoiceses() {
        return this.customerChildInvoiceses;
    }
    
    public void setCustomerChildInvoiceses(Set customerChildInvoiceses) {
        this.customerChildInvoiceses = customerChildInvoiceses;
    }




}


