package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1




/**
 * Foods generated by hbm2java
 */
public class Foods  implements java.io.Serializable {


     private int id;
     private SubMenus subMenus;
     private String foodName;
     private Integer isRequire;
     private String image;

    public Foods() {
    }

	
    public Foods(int id) {
        this.id = id;
    }
    public Foods(int id, SubMenus subMenus, String foodName, Integer isRequire, String image) {
       this.id = id;
       this.subMenus = subMenus;
       this.foodName = foodName;
       this.isRequire = isRequire;
       this.image = image;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SubMenus getSubMenus() {
        return this.subMenus;
    }
    
    public void setSubMenus(SubMenus subMenus) {
        this.subMenus = subMenus;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }
    public Integer getIsRequire() {
        return this.isRequire;
    }
    
    public void setIsRequire(Integer isRequire) {
        this.isRequire = isRequire;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


