package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1
//TriThoai Changed


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * MaterialCategories generated by hbm2java
 */
public class MaterialCategories  implements java.io.Serializable {


     private int id;
     private String idStr;

     private Suppliers suppliers;
     private String categoryName;
     private Set materialses = new HashSet(0);

    public MaterialCategories() {
    }
    
    public String getIdStr() {
        return idStr;
    }

    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }
    public MaterialCategories(int id) {
        this.id = id;
    }
    public MaterialCategories(int id, Suppliers suppliers, String categoryName, Set materialses) {
       this.id = id;
       this.suppliers = suppliers;
       this.categoryName = categoryName;
       this.materialses = materialses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getMaterialses() {
        return this.materialses;
    }
    
    public void setMaterialses(Set materialses) {
        this.materialses = materialses;
    }




}


