package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Materials generated by hbm2java
 */
public class Materials  implements java.io.Serializable {


     private int id;
     private MaterialCategories materialCategories;
     private String materialName;
     private Double materialPricePerUnit;
     private String materialUnit;

    public Materials() {
    }

	
    public Materials(int id) {
        this.id = id;
    }
    public Materials(int id, MaterialCategories materialCategories, String materialName, Double materialPricePerUnit, String materialUnit) {
       this.id = id;
       this.materialCategories = materialCategories;
       this.materialName = materialName;
       this.materialPricePerUnit = materialPricePerUnit;
       this.materialUnit = materialUnit;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public MaterialCategories getMaterialCategories() {
        return this.materialCategories;
    }
    
    public void setMaterialCategories(MaterialCategories materialCategories) {
        this.materialCategories = materialCategories;
    }
    public String getMaterialName() {
        return this.materialName;
    }
    
    public void setMaterialName(String materialName) {
        this.materialName = materialName;
    }
    public Double getMaterialPricePerUnit() {
        return this.materialPricePerUnit;
    }
    
    public void setMaterialPricePerUnit(Double materialPricePerUnit) {
        this.materialPricePerUnit = materialPricePerUnit;
    }
    public String getMaterialUnit() {
        return this.materialUnit;
    }
    
    public void setMaterialUnit(String materialUnit) {
        this.materialUnit = materialUnit;
    }




}


