package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menus generated by hbm2java
 */
public class Menus  implements java.io.Serializable {


     private int id;
     private CategoryTypes categoryTypes;
     private Caterers caterers;
     private String menuName;
     private Double costPerPlate;
     private Integer minPlate;
     private Integer maxPlate;
     private String image;
     private Set subMenuses = new HashSet(0);

    public Menus() {
    }

	
    public Menus(int id) {
        this.id = id;
    }
    public Menus(int id, CategoryTypes categoryTypes, Caterers caterers, String menuName, Double costPerPlate, Integer minPlate, Integer maxPlate, String image, Set subMenuses) {
       this.id = id;
       this.categoryTypes = categoryTypes;
       this.caterers = caterers;
       this.menuName = menuName;
       this.costPerPlate = costPerPlate;
       this.minPlate = minPlate;
       this.maxPlate = maxPlate;
       this.image = image;
       this.subMenuses = subMenuses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CategoryTypes getCategoryTypes() {
        return this.categoryTypes;
    }
    
    public void setCategoryTypes(CategoryTypes categoryTypes) {
        this.categoryTypes = categoryTypes;
    }
    public Caterers getCaterers() {
        return this.caterers;
    }
    
    public void setCaterers(Caterers caterers) {
        this.caterers = caterers;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public Double getCostPerPlate() {
        return this.costPerPlate;
    }
    
    public void setCostPerPlate(Double costPerPlate) {
        this.costPerPlate = costPerPlate;
    }
    public Integer getMinPlate() {
        return this.minPlate;
    }
    
    public void setMinPlate(Integer minPlate) {
        this.minPlate = minPlate;
    }
    public Integer getMaxPlate() {
        return this.maxPlate;
    }
    
    public void setMaxPlate(Integer maxPlate) {
        this.maxPlate = maxPlate;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getSubMenuses() {
        return this.subMenuses;
    }
    
    public void setSubMenuses(Set subMenuses) {
        this.subMenuses = subMenuses;
    }




}


