package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private int id;
     private Accounts accounts;
     private Countries countries;
     private String supplierName;
     private String supplierEmail;
     private String supplierPhoneNumber;
     private String supplierAddress;
     private String supplierDescription;
     private Set materialCategorieses = new HashSet(0);
     private Set supplierInvoiceses = new HashSet(0);

    public Suppliers() {
    }

	
    public Suppliers(int id) {
        this.id = id;
    }
    public Suppliers(int id, Accounts accounts, Countries countries, String supplierName, String supplierEmail, String supplierPhoneNumber, String supplierAddress, String supplierDescription, Set materialCategorieses, Set supplierInvoiceses) {
       this.id = id;
       this.accounts = accounts;
       this.countries = countries;
       this.supplierName = supplierName;
       this.supplierEmail = supplierEmail;
       this.supplierPhoneNumber = supplierPhoneNumber;
       this.supplierAddress = supplierAddress;
       this.supplierDescription = supplierDescription;
       this.materialCategorieses = materialCategorieses;
       this.supplierInvoiceses = supplierInvoiceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Accounts getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Accounts accounts) {
        this.accounts = accounts;
    }
    public Countries getCountries() {
        return this.countries;
    }
    
    public void setCountries(Countries countries) {
        this.countries = countries;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getSupplierEmail() {
        return this.supplierEmail;
    }
    
    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }
    public String getSupplierPhoneNumber() {
        return this.supplierPhoneNumber;
    }
    
    public void setSupplierPhoneNumber(String supplierPhoneNumber) {
        this.supplierPhoneNumber = supplierPhoneNumber;
    }
    public String getSupplierAddress() {
        return this.supplierAddress;
    }
    
    public void setSupplierAddress(String supplierAddress) {
        this.supplierAddress = supplierAddress;
    }
    public String getSupplierDescription() {
        return this.supplierDescription;
    }
    
    public void setSupplierDescription(String supplierDescription) {
        this.supplierDescription = supplierDescription;
    }
    public Set getMaterialCategorieses() {
        return this.materialCategorieses;
    }
    
    public void setMaterialCategorieses(Set materialCategorieses) {
        this.materialCategorieses = materialCategorieses;
    }
    public Set getSupplierInvoiceses() {
        return this.supplierInvoiceses;
    }
    
    public void setSupplierInvoiceses(Set supplierInvoiceses) {
        this.supplierInvoiceses = supplierInvoiceses;
    }




}


