package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SupplierInvoices generated by hbm2java
 */
public class SupplierInvoices  implements java.io.Serializable {


     private int id;
     private Caterers caterers;
     private Suppliers suppliers;
     private String invoiceDate;
     private String deliveryDate;
     private String status;
     private Set supplierChildInvoiceses = new HashSet(0);

    public SupplierInvoices() {
    }

	
    public SupplierInvoices(int id) {
        this.id = id;
    }
    public SupplierInvoices(int id, Caterers caterers, Suppliers suppliers, String invoiceDate, String deliveryDate, String status, Set supplierChildInvoiceses) {
       this.id = id;
       this.caterers = caterers;
       this.suppliers = suppliers;
       this.invoiceDate = invoiceDate;
       this.deliveryDate = deliveryDate;
       this.status = status;
       this.supplierChildInvoiceses = supplierChildInvoiceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Caterers getCaterers() {
        return this.caterers;
    }
    
    public void setCaterers(Caterers caterers) {
        this.caterers = caterers;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(String invoiceDate) {
        this.invoiceDate = invoiceDate;
    }
    public String getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(String deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getSupplierChildInvoiceses() {
        return this.supplierChildInvoiceses;
    }
    
    public void setSupplierChildInvoiceses(Set supplierChildInvoiceses) {
        this.supplierChildInvoiceses = supplierChildInvoiceses;
    }




}


