package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Workers generated by hbm2java
 */
public class Workers  implements java.io.Serializable {


     private int id;
     private String idStr;
     private String checked;
     private WorkerTypes workerTypes;
     private String workerName;
     private String workerPhoneNumber;
     private String workerEmail;
     private String workerAddress;
     private String workerDateOfJoin;
     private Integer status;
     private String statusStr;
     private Set workerSalarieses = new HashSet(0);
     private Set customerInvoiceses = new HashSet(0);

    public Workers() {
    }

	
    public Workers(int id) {
        this.id = id;
    }    
    
    public String getIdStr() {
        return idStr;
    }

    public String getStatusStr() {
        return statusStr;
    }

    public String getChecked() {
        return checked;
    }

    public void setChecked(String checked) {
        this.checked = checked;
    }

    public void setStatusStr(String statusStr) {
        this.statusStr = statusStr;
    }

    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }
    public Workers(int id, WorkerTypes workerTypes, String workerName, String workerPhoneNumber, String workerEmail, String workerAddress, String workerDateOfJoin, Integer status, Set workerSalarieses, Set customerInvoiceses) {
       this.id = id;
       this.workerTypes = workerTypes;
       this.workerName = workerName;
       this.workerPhoneNumber = workerPhoneNumber;
       this.workerEmail = workerEmail;
       this.workerAddress = workerAddress;
       this.workerDateOfJoin = workerDateOfJoin;
       this.status = status;
       this.workerSalarieses = workerSalarieses;
       this.customerInvoiceses = customerInvoiceses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public WorkerTypes getWorkerTypes() {
        return this.workerTypes;
    }
    
    public void setWorkerTypes(WorkerTypes workerTypes) {
        this.workerTypes = workerTypes;
    }
    public String getWorkerName() {
        return this.workerName;
    }
    
    public void setWorkerName(String workerName) {
        this.workerName = workerName;
    }
    public String getWorkerPhoneNumber() {
        return this.workerPhoneNumber;
    }
    
    public void setWorkerPhoneNumber(String workerPhoneNumber) {
        this.workerPhoneNumber = workerPhoneNumber;
    }
    public String getWorkerEmail() {
        return this.workerEmail;
    }
    
    public void setWorkerEmail(String workerEmail) {
        this.workerEmail = workerEmail;
    }
    public String getWorkerAddress() {
        return this.workerAddress;
    }
    
    public void setWorkerAddress(String workerAddress) {
        this.workerAddress = workerAddress;
    }
    public String getWorkerDateOfJoin() {
        return this.workerDateOfJoin;
    }
    
    public void setWorkerDateOfJoin(String workerDateOfJoin) {
        this.workerDateOfJoin = workerDateOfJoin;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getWorkerSalarieses() {
        return this.workerSalarieses;
    }
    
    public void setWorkerSalarieses(Set workerSalarieses) {
        this.workerSalarieses = workerSalarieses;
    }
    public Set getCustomerInvoiceses() {
        return this.customerInvoiceses;
    }
    
    public void setCustomerInvoiceses(Set customerInvoiceses) {
        this.customerInvoiceses = customerInvoiceses;
    }




}


