package model.pojo;
// Generated Jul 14, 2015 10:47:49 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * WorkerTypes generated by hbm2java
 */
public class WorkerTypes  implements java.io.Serializable {


     private int id;
     private String idStr;
     private Caterers caterers;
     private String workerTypeName;
     private Double payPerDay;
     private Set workerses = new HashSet(0);

    public WorkerTypes() {
    }

	

    public String getIdStr() {
        return idStr;
    }

    public void setIdStr(String idStr) {
        this.idStr = idStr;
    }
    
    public WorkerTypes(int id) {
        this.id = id;
    }
    public WorkerTypes(int id, Caterers caterers, String workerTypeName, Double payPerDay, Set workerses) {
       this.id = id;
       this.caterers = caterers;
       this.workerTypeName = workerTypeName;
       this.payPerDay = payPerDay;
       this.workerses = workerses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Caterers getCaterers() {
        return this.caterers;
    }
    
    public void setCaterers(Caterers caterers) {
        this.caterers = caterers;
    }
    public String getWorkerTypeName() {
        return this.workerTypeName;
    }
    
    public void setWorkerTypeName(String workerTypeName) {
        this.workerTypeName = workerTypeName;
    }
    public Double getPayPerDay() {
        return this.payPerDay;
    }
    
    public void setPayPerDay(Double payPerDay) {
        this.payPerDay = payPerDay;
    }
    public Set getWorkerses() {
        return this.workerses;
    }
    
    public void setWorkerses(Set workerses) {
        this.workerses = workerses;
    }




}


